[package]
name = "windortortent"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
windows = { version = "0.62", features = [
  "Management_Deployment",
  "ApplicationModel",
  "Win32_UI_Shell",
  "Win32_System_Registry",
  "Win32_UI_WindowsAndMessaging",
  "Win32_Security",
  "Win32_System_Com",
  "Win32_System_Threading",
  "Win32_System_Antimalware",
  "Win32_Security_Authorization",
  "Win32_System_ApplicationInstallationAndServicing",
] }
tokio = { version = "1", features = [
  "fs",
  "process",
  "time",
  "test-util",
  "macros",
] }
zip = { version = "7" }
windows-core = "0.62"
windows-future = "0.3"
serde = { version = "1", features = ["derive"] }
serde-xml-rs = "0.8"

toml = { version = "0.9" }

rhai = { version = "1", features = ["no_std", "serde"] }
windows-registry = { version = "0.6" }
regex = "1.12.2"

[features]
default = []
legacy-experimental-ahqdb = []
